services:
  moodleapp:
    build:
      context: .
    image: ghcr.io/monkeysoftnl/moodleapp:latest
    container_name: moodleapp
    ports:
      - 80:80
    volumes:
      - moodledata:/var/www/moodledata
    environment:
      MOODLE_DBTYPE: mariadb
      MOODLE_DBHOST: moodledb
      MOODLE_DBNAME: ${MYSQL_DATABASE}
      MOODLE_DBUSER: ${MYSQL_USER}
      MOODLE_DBPASS: ${MYSQL_PASSWORD}
      MOODLE_DBPREFIX: mdl_
      MOODLE_DBPORT: 3306
      MOODLE_WWWROOT: ${MOODLE_WWWROOT}
    depends_on:
      - moodledb

  moodledb:
    image: mysql:latest
    container_name: moodledb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: moodledb
      PMA_PORT: 3306
    depends_on:
      - moodledb

volumes:
  dbdata:
  moodledata: